- code_git_repo: paritytech/polkadot-sdk
  code_git_ref: alexggh/statement-store-not-api
  debian-versions:
    - trixie
  rust-versions:
    - "1.88.0"
  clang-versions:
    - 20
  rustc-targets:
    - x86-64-v3
  components:
    - substrate-node
